# Generated by Django 5.0.7 on 2025-07-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_product'),
        ('store', '0004_product_subcategory_alter_product_subsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_products_by_subcategory', to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_products_by_subsubcategory', to='category.subsubcategory'),
        ),
    ]
