# Generated by Django 5.2.4 on 2025-07-28 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('applicable_products', models.ManyToManyField(related_name='coupons', to='store.product')),
            ],
            options={
                'ordering': ('-valid_from',),
            },
        ),
    ]
