# Generated by Django 5.2.4 on 2025-08-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_alter_coupon_options_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
