# Generated by Django 5.2.4 on 2025-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_coupon_deliverymethod_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
