# Generated by Django 4.2.23 on 2025-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestdeal',
            options={},
        ),
        migrations.RemoveField(
            model_name='bestdeal',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='bestdeal',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bestdeal',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bestdeal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
