# Generated by Django 5.0.7 on 2025-07-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('sub_sub_category_images', models.ImageField(blank=True, upload_to='photos/subsubcategories')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='category.subcategory')),
            ],
            options={
                'verbose_name': 'subsubcategory',
                'verbose_name_plural': 'subsubcategories',
                'unique_together': {('sub_category', 'sub_sub_category_name')},
            },
        ),
    ]
