# Generated by Django 5.0.7 on 2025-07-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
