# Generated by Django 5.2.4 on 2025-11-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Product'},
        ),
    ]
