# Generated by Django 5.2.4 on 2025-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bkash_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_merchant_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
